import 'dart:convert';

/// A single HTTP cookie used for TikTok session export.
class TikTokCookie {
  const TikTokCookie({
    required this.name,
    required this.value,
    required this.domain,
    this.path = '/',
    this.expiresEpoch = 0,
    this.isSecure = true,
    this.isHttpOnly = false,
  });

  final String name;
  final String value;
  final String domain;
  final String path;
  final int expiresEpoch;
  final bool isSecure;
  final bool isHttpOnly;

  Map<String, Object?> toJson() => {
        'name': name,
        'value': value,
        'domain': domain,
        'path': path,
        'expiresEpoch': expiresEpoch,
        'isSecure': isSecure,
        'isHttpOnly': isHttpOnly,
      };

  factory TikTokCookie.fromJson(Map<String, Object?> json) {
    return TikTokCookie(
      name: json['name']?.toString() ?? '',
      value: json['value']?.toString() ?? '',
      domain: json['domain']?.toString() ?? '.tiktok.com',
      path: json['path']?.toString() ?? '/',
      expiresEpoch: _asInt(json['expiresEpoch']),
      isSecure: json['isSecure'] == true,
      isHttpOnly: json['isHttpOnly'] == true,
    );
  }

  static int _asInt(Object? value) {
    if (value is int) return value;
    return int.tryParse(value?.toString() ?? '') ?? 0;
  }
}

String tiktokCookieHeader(Iterable<TikTokCookie> cookies) {
  final parts = <String>[];
  for (final cookie in cookies) {
    if (cookie.name.isEmpty) continue;
    parts.add('${cookie.name}=${cookie.value}');
  }
  return parts.join('; ');
}

bool tiktokSessionLooksLoggedIn(Iterable<TikTokCookie> cookies) {
  final names = {for (final c in cookies) c.name};
  return names.contains('sessionid');
}

String tiktokNetscapeCookieFileContents(Iterable<TikTokCookie> cookies) {
  final buffer = StringBuffer()
    ..writeln('# Netscape HTTP Cookie File')
    ..writeln('# This file was generated by Geonode Download Manager.')
    ..writeln('# https://curl.se/docs/http-cookies.html')
    ..writeln();

  for (final cookie in cookies) {
    if (cookie.name.isEmpty) continue;
    var domain = cookie.domain.trim();
    if (domain.isEmpty) domain = '.tiktok.com';
    final includeSubdomains = domain.startsWith('.') ? 'TRUE' : 'FALSE';
    if (!domain.startsWith('.') &&
        (domain == 'tiktok.com' || domain.endsWith('.tiktok.com'))) {
      domain = '.$domain';
    }
    final path = cookie.path.isEmpty ? '/' : cookie.path;
    final secure = cookie.isSecure ? 'TRUE' : 'FALSE';
    final expires = cookie.expiresEpoch > 0 ? cookie.expiresEpoch : 0;
    buffer.writeln(
      '$domain\t$includeSubdomains\t$path\t$secure\t$expires\t'
      '${cookie.name}\t${cookie.value}',
    );
  }
  return buffer.toString();
}

List<TikTokCookie> decodeTikTokCookiesJson(String raw) {
  if (raw.trim().isEmpty) return const [];
  final decoded = jsonDecode(raw);
  if (decoded is! List) return const [];
  return decoded
      .whereType<Map>()
      .map((item) => TikTokCookie.fromJson(item.cast<String, Object?>()))
      .where((c) => c.name.isNotEmpty)
      .toList();
}

String encodeTikTokCookiesJson(Iterable<TikTokCookie> cookies) {
  return jsonEncode([for (final c in cookies) c.toJson()]);
}
